### ISSUE TITLE
Switching explorer configuration from testnet to mainnet does not work

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s-ts#11]
I posted this announcement to the test explorer on 037cf5d083b58ad971d7943ecfa8bee797ee68ee and it failed to switch the oracle configuration over

![Screenshot from 2021-09-21 12-41-47](https://user-images.githubusercontent.com/3514957/134220765-ace6d0a9-1c97-42f9-aed3-b77da7d83ccf.png)

![Screenshot from 2021-09-21 12-42-17](https://user-images.githubusercontent.com/3514957/134220762-aec4ba33-3ee3-4c6c-97b2-117864afce36.png)

and this is what I see on the _testnet_ explorer logs which makes sense since i've posted it there once already

![Screenshot from 2021-09-21 12-40-54](https://user-images.githubusercontent.com/3514957/134220545-b3b8cc43-d19e-48e7-a8cc-e4d4fe141a14.png)

**Comment by user411** [comment]
I put another commit on proxy-server-002 that should address this behavior.

**Comment by Christewart** [comment]
fixed in #10
