### ISSUE TITLE
Layout of landing page doesn't show network information by default

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s-ts#48]
This screenshots are taken on  c4296586f57f34278927f699f590cafbf1802ad7 

When I land on my home page, i can't see things like the tor address, the block height, fee rate etc on the home page. On our desktop app, we always display those on the bottom of the page. We might want to move these to the top so a user sees these when they open up the app?

![Screenshot from 2021-12-06 10-56-29](https://user-images.githubusercontent.com/3514957/144888715-9417f9b4-cf8a-46ad-ab86-1ec017b770fb.png)

![Screenshot from 2021-12-06 10-55-47](https://user-images.githubusercontent.com/3514957/144888351-9b44f8d1-77ea-4556-8b0a-36d73f063b4c.png)

![Screenshot from 2021-12-06 10-59-52](https://user-images.githubusercontent.com/3514957/144888979-41163503-2d07-458a-a5ed-c1ee659abc67.png)

**Comment by user411** [comment]
This has been addressed with the addition of the header nav.
