### ISSUE TITLE
Consider adding links out to the oracle explorer with example contracts

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s-ts#62]
A user could come to this screen and not understand what an offer is, if we link out to existing contracts on the oracle explorer to get an idea of what they look like and that they can copy them into the text field

Maybe this link: https://oracle.suredbits.com/contract/enum

My proposed text

```
New to DLCs? Check out our [youtube tutorial](https://www.youtube.com/watch?v=oR0I0aHxNMM) or go grab a contract from the [Suredbits Contract Explorer](https://oracle.suredbits.com/contract/enum)
```

As mentioned on our call, the youtube video is going to need to be updated for the new UI on umbrel

![Screenshot from 2022-01-25 12-41-19](https://user-images.githubusercontent.com/3514957/151038805-d0ed41e7-d7a9-4289-bb17-4c141d618a6e.png)

**Comment by user411** [comment]
This was addressed when adding the FAQ.
