### ISSUE TITLE
Cannot always sign outcomes on krystal bull

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s-ts#66]
I've attached a screencast where i can only sign the first outcome of an event on Krystal Bull. This was run on a0bbe69 which is a bit old, so perhaps this is fixed in master. This is our last official release of Krystal Bull on umbrel i believe

![Screencast from 01-27-2022 09 22 29 AM](https://user-images.githubusercontent.com/3514957/151389467-5b1e6229-8fc1-4e26-9678-9b740763cf59.gif)

**Comment by user411** [comment]
Fixed in https://github.com/bitcoin-s/bitcoin-s-ts/pull/68
