### ISSUE TITLE
Add warning for wallet rescans on umbrel

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s-ts#78]
Add a warning for how much time they can take. Also mention that your balances will disappear for the duration of the rescan.

![Screenshot from 2022-02-04 08-53-48](https://user-images.githubusercontent.com/3514957/152550318-1a171094-a7a3-4ac0-969d-06307d1c6fa7.png)

**Comment by Christewart** [comment]
Probably better to address the root cause, we will see how long it takes us to implement: https://github.com/bitcoin-s/bitcoin-s/issues/4044

**Comment by user411** [comment]
Fixed by https://github.com/bitcoin-s/bitcoin-s-ts/pull/79
